version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: chalk
    versions:
    - ">= 4.0.a"
    - "< 4.1"
  - dependency-name: chalk
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: ora
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: prettier
    versions:
    - ">= 2.0.a"
    - "< 2.1"
  - dependency-name: prettier
    versions:
    - ">= 2.1.a"
    - "< 2.2"
  - dependency-name: yargs
    versions:
    - ">= 16.a"
    - "< 17"
